#! /bin/sh
case "$1" in
    start)
        mknod -m 0666 /dev/null c 1 3
	mknod -m 0666 /dev/ttyS0 c 204 64
        echo -n "Populating $udev_root using udev: "
        echo -e '\000\000\000\000' > /proc/sys/kernel/hotplug
        $UDEV_BIN -d || (echo "FAIL" && exit 1)
	$UDEVSTART_BIN || (echo "FAIL" && exit 1)
        echo "done"
        ;;
    stop)
        # Stop execution of events
        udevcontrol stop_exec_queue
        killall udevd
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
